version: '2'
services:
    lhs_shadowsocks:
        container_name: shadowsocks
        image: "${DOCKER_USER}/shadowsocks"
        build:
            context: .
            dockerfile: Dockerfile.shadowsocks
        environment:
            TZ: 'Asia/Shanghai'
        ports:
            - "8380:8380"
            - "8381:8381"
            - "8382:8382"
            - "8383:8383"
            - "8384:8384"
            - "8385:8385"
            - "8386:8386"
            - "8387:8387"
            - "8388:8388"
            - "8389:8389"
        restart: always